#SPDX-License-Identifier: MIT-0
---
# tasks file for borgbackup
- name: Download and install scripts
  block:
    - name: Make sure the scripts folder exists - {{ scriptsfolder }}
      file: 
        path: "{{ scriptsfolder }}"
        state: directory
        mode: '0755'

    - name: Clear the scripts folder - {{ scriptsfolder }}
      shell: "rm -rf {{ scriptsfolder }}/*"

    - name: Restore scripts folder - {{ scriptsfolder }}
      environment:
        BORG_RSH: "{{ BORG_RSH }}"
        BORG_REPO: "{{ BORG_REPO }}"
        BORG_PASSPHRASE: "{{ BORG_PASSPHRASE }}"
      shell:
        cmd: "borg extract --strip-components 2 -v --list {{ BORG_REPO }}::{{ VERSION }} {{ scriptsfolder }}"
        chdir: "{{ scriptsfolder }}"
      async: 3600
      poll: 10

- name: Cronjobs
  block:
    - name: Edit Crontab for Borg Backup Cloud
      cron:
        name: Borg Backup Cloud
        minute: "0"
        hour: "0"
        job: "{{ scriptsfolder }}/borgbackup.sh"

    - name: Mirror crontab job
      cron:
        name: Mirror sync job
        minute: "0"
        hour: "2"
        job: "{{ scriptsfolder }}/sync.sh"

    - name: Duckdns crontab job
      cron:
        name: Duckdns job
        special_time: reboot
        job: "sleep 300 && {{ scriptsfolder }}/duckdns.sh"

    - name: Hetzner auto dns crontab job
      cron:
        name: Hetzner auto dns
        special_time: reboot
        job: "sleep 300 && {{ scriptsfolder }}/hetznerchangednsscript.sh"