- name: Server Ansible Script
  become: yes
  become_user: root
  hosts: all
  vars_files:
    - inventory/vars/secrets.yml
  roles:
    - core/config/install_packages
    - core/config/create_users
    - core/config/install_keys
    #- core/config/install_steamcmd
    - docker/install_docker
    - docker/config_docker
    - core/restore_hetzner/repo_check
    - core/restore_hetzner/restore_caddy
    #- core/restore_hetzner/restore_opt
    - core/restore_hetzner/restore_samba
    - core/restore_hetzner/restore_scripts
    #- core/restore_hetzner/restore_service_files
    - core/restore_hetzner/restore_websites
    - core/restore_hetzner/restore_wireguard
    #- core/execution/setup_crons
    #- core/execution/start_caddy
    #- core/execution/start_samba
    #- core/execution/start_wireguard
    - tests/caddy_tests
    - tests/keys_tests