- name: Server Ansible Script
  become: yes
  become_user: root
  hosts: all
  vars_files:
    - inventory/vars/secrets.yml
  roles:
    - core/other/packages
    - core/other/users
    - core/other/keys
    - core/restore_hetzner/caddy
    - core/restore_hetzner/scripts
    - core/other/cron
    - core/restore_hetzner/restore_opt
    - core/restore_hetzner/wireguard
    - docker/install_docker
    - docker/containers
    - core/restore_hetzner/restore_service_files
    - core/restore_hetzner/websites
    - core/restore_hetzner/samba
    - core/other/install_steamcmd