- name: Server Ansible Script
  become: yes
  become_user: root
  hosts: all
  vars_files:
    - inventory/vars/secrets.yml
  roles:
    - config/install_packages
    - config/create_users
    - config/config_podman
    - config/install_steamcmd
    - restore/repo_check
    - restore/restore_caddy
    - restore/restore_cron
    - restore/restore_keys
    - restore/restore_opt
    - restore/restore_samba
    - restore/restore_scripts
    - restore/restore_ssh
    - restore/restore_websites
    - restore/restore_wireguard
    - execution/start_services
    - execution/start_podman