- name: Start services
  block:
    - name: Restart caddy
      service:
        enabled: true
        name: caddy
        state: started

    - name: Restart samba
      systemd:
        enabled: true
        name: smbd
        state: started

    - name: Enable and start wireguard
      systemd:
        name: "wg-quick@wg0"
        enabled: true
        state: started

    - name: Enable and start ssh
      systemd:
        name: ssh
        enabled: true
        state: started