#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/services

- name: Download and install services
  block:
    - name: Clear the services folder - {{ servicesfolder }}
      shell: "rm -rf {{ servicesfolder }}/*"

    - name: Restore services folder - {{ servicesfolder }}
      environment:
        BORG_RSH: "{{ BORG_RSH }}"
        BORG_REPO: "{{ BORG_REPO }}"
        BORG_PASSPHRASE: "{{ BORG_PASSPHRASE }}"
      shell:
        cmd: "borg extract --strip-components 1 -v --list {{ BORG_REPO }}::{{ VERSION }} {{ servicesfolder }}"
        chdir: "{{ servicesfolder }}"
      async: 3600
      poll: 10

- name: wireguard
  block:
    - name: Install wireguard
      apt:
        name: wireguard
        update_cache: true
        state: present

    - name: Restore wireguard config from backup
      environment:
        BORG_RSH: "{{ BORG_RSH }}"
        BORG_REPO: "{{ BORG_REPO }}"
        BORG_PASSPHRASE: "{{ BORG_PASSPHRASE }}"
      shell:
        cmd: "borg extract --strip-components 2 -v --list {{ BORG_REPO }}::{{ VERSION }} {{ wireguardconfig }}"
        chdir: "{{ wireguardconfig }}"
      async: 3600
      poll: 10

    - name: Enable and start wireguard
      systemd:
        name: "wg-quick@wg0"
        enabled: true
        state: restarted

- name: Samba
  block:
    - name: Ensure samba folder exists
      file: 
        path: "{{ sambaconfigfolder }}"
        state: directory
        mode: '0755'

    - name: Change the file permissions for samba
      file:
        path: "{{ sambaconfigfolder }}"
        state: directory
        recurse: yes
        owner: root
        group: root

    - name: Clear the samba config folder - {{ sambaconfigfolder }}
      shell: "rm -rf {{ sambaconfigfolder }}/*"

    - name: Restore samba config folder - {{ sambaconfigfolder }}
      environment:
        BORG_RSH: "{{ BORG_RSH }}"
        BORG_REPO: "{{ BORG_REPO }}"
        BORG_PASSPHRASE: "{{ BORG_PASSPHRASE }}"
      shell:
        cmd: "borg extract --strip-components 2 -v --list {{ BORG_REPO }}::{{ VERSION }} {{ sambaconfigfolder }}"
        chdir: "{{ sambaconfigfolder }}"
      async: 3600
      poll: 10

    - name: Restart samba
      systemd:
        name: smbd
        state: restarted

- name: Services
  block:
    - name: Copy services
      environment:
        BORG_RSH: "{{ BORG_RSH }}"
        BORG_REPO: "{{ BORG_REPO }}"
        BORG_PASSPHRASE: "{{ BORG_PASSPHRASE }}"
      shell:
        cmd: "borg extract --strip-components 3 -v --list {{ BORG_REPO }}::{{ VERSION }} /etc/systemd/system"
        chdir: "/etc/systemd/system"
      async: 3600
      poll: 10

    - name: Enable and start services
      systemd:
        name: "{{ item }}"
        enabled: true
        state: started
      loop: "{{ services }}"