- name: Create podman network
  block:
    - name: Create podman network
      become: true
      become_user: dockeruser
      community.docker.docker_network:
        name: docker-network
        state: present
        ipam_config:
          - subnet: 172.0.0.0/24