VERSION: 2026-05-25_15:05
websitefolder: /var/www/html
scriptsfolder: /etc/scripts
sambaconfigfolder: /etc/samba
caddyfolder: /etc/caddy
wireguardconfig: /etc/wireguard
BORG_RSH: "ssh -p 22 -i /root/.ssh/voyager1 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
BORG_REPO: "ssh://jan@192.168.0.166:22/mnt/HDD/garcon-backup"
ansible_ssh_private_key_file: "~/.ssh/JANSERVER"
users_no_home:
  - ignas
  - steam
  - dockeruser
samba_users:
  - jan
  - ignas
containers:
  - dockge
packages:
  - sudo
  - ca-certificates
  - curl
  - rsync
  - borgbackup
  - cockpit
  - caddy
  - netfilter-persistent
  - iptables
  - samba
  - vim
  - ncdu
  - ssh
  - tree
  - podman
  - podman-compose